

services:
  srv_dev_XX:
    image: ubuntu:22.04
    container_name: srv_dev_XX
    command: tail -f /dev/null
    volumes:
      - datos_devXX:/var/empresa
    networks:
      - net_dev_XX

volumes:
  datos_devXX:

networks:
  net_dev_XX:




  
